# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\napp_server\x1a\x0c\x63ommon.proto\"\x90\x01\n\x11\x43reateTaskRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0b\n\x03\x64ue\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\t\x12\x11\n\tassigners\x18\x05 \x03(\t\x12\x13\n\x0b\x61ssigneeIds\x18\x06 \x03(\x05\x12\x11\n\tmessageId\x18\x07 \x01(\x05\x32S\n\x0bTaskService\x12\x44\n\x06\x43reate\x12\x1d.app_server.CreateTaskRequest\x1a\x1b.app_server.SuccessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATETASKREQUEST']._serialized_start=41
  _globals['_CREATETASKREQUEST']._serialized_end=185
  _globals['_TASKSERVICE']._serialized_start=187
  _globals['_TASKSERVICE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
