# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inquiry.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'inquiry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rinquiry.proto\x12\napp_server\x1a\x0c\x63ommon.proto\"Z\n\x14\x43reateInquiryRequest\x12\x11\n\tmessageId\x18\x01 \x01(\x05\x12\r\n\x05types\x18\x02 \x03(\t\x12\x10\n\x08question\x18\x03 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x04 \x01(\t2Y\n\x0eInquiryService\x12G\n\x06\x43reate\x12 .app_server.CreateInquiryRequest\x1a\x1b.app_server.SuccessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inquiry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEINQUIRYREQUEST']._serialized_start=43
  _globals['_CREATEINQUIRYREQUEST']._serialized_end=133
  _globals['_INQUIRYSERVICE']._serialized_start=135
  _globals['_INQUIRYSERVICE']._serialized_end=224
# @@protoc_insertion_point(module_scope)
