# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\napp_server\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x8e\x01\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x0f\n\x07picture\x18\x05 \x01(\t\x12\x10\n\x08isActive\x18\x06 \x01(\x08\x12\x11\n\tcreatedAt\x18\x07 \x01(\t\x12\x11\n\tupdatedAt\x18\x08 \x01(\t\"*\n\x17\x46indOneByKeywordRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"#\n\x12VerifyTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x84\x01\n\x13VerifyTokenResponse\x12=\n\x07payload\x18\x01 \x03(\x0b\x32,.app_server.VerifyTokenResponse.PayloadEntry\x1a.\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xb0\x01\n\x0b\x41uthService\x12N\n\x0bVerifyToken\x12\x1e.app_server.VerifyTokenRequest\x1a\x1f.app_server.VerifyTokenResponse\x12Q\n\x10\x46indOneByKeyword\x12#.app_server.FindOneByKeywordRequest\x1a\x18.app_server.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VERIFYTOKENRESPONSE_PAYLOADENTRY']._options = None
  _globals['_VERIFYTOKENRESPONSE_PAYLOADENTRY']._serialized_options = b'8\001'
  _globals['_USERRESPONSE']._serialized_start=86
  _globals['_USERRESPONSE']._serialized_end=228
  _globals['_FINDONEBYKEYWORDREQUEST']._serialized_start=230
  _globals['_FINDONEBYKEYWORDREQUEST']._serialized_end=272
  _globals['_VERIFYTOKENREQUEST']._serialized_start=274
  _globals['_VERIFYTOKENREQUEST']._serialized_end=309
  _globals['_VERIFYTOKENRESPONSE']._serialized_start=312
  _globals['_VERIFYTOKENRESPONSE']._serialized_end=444
  _globals['_VERIFYTOKENRESPONSE_PAYLOADENTRY']._serialized_start=398
  _globals['_VERIFYTOKENRESPONSE_PAYLOADENTRY']._serialized_end=444
  _globals['_AUTHSERVICE']._serialized_start=447
  _globals['_AUTHSERVICE']._serialized_end=623
# @@protoc_insertion_point(module_scope)
