# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: class_registration.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'class_registration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63lass_registration.proto\x12\napp_server\x1a\x0c\x63ommon.proto\"l\n\x1d\x43reateRegistrationItemRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x13\n\x0bsubjectName\x18\x02 \x01(\t\x12\x11\n\tclassName\x18\x03 \x01(\t\x12\x13\n\x0bsubjectCode\x18\x04 \x01(\t\"h\n\x19\x43reateRegistrationRequest\x12\x11\n\tmessageId\x18\x01 \x01(\x05\x12\x38\n\x05items\x18\x04 \x03(\x0b\x32).app_server.CreateRegistrationItemRequest2h\n\x18\x43lassRegistrationService\x12L\n\x06\x43reate\x12%.app_server.CreateRegistrationRequest\x1a\x1b.app_server.SuccessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'class_registration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEREGISTRATIONITEMREQUEST']._serialized_start=54
  _globals['_CREATEREGISTRATIONITEMREQUEST']._serialized_end=162
  _globals['_CREATEREGISTRATIONREQUEST']._serialized_start=164
  _globals['_CREATEREGISTRATIONREQUEST']._serialized_end=268
  _globals['_CLASSREGISTRATIONSERVICE']._serialized_start=270
  _globals['_CLASSREGISTRATIONSERVICE']._serialized_end=374
# @@protoc_insertion_point(module_scope)
