# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: label.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blabel.proto\x12\napp_server\">\n\x13UpdateLabelsRequest\x12\x11\n\tmessageId\x18\x01 \x01(\x03\x12\x14\n\x0csystemLabels\x18\x02 \x03(\t\"8\n\x14UpdateLabelsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2c\n\x0eMessageService\x12Q\n\x0cUpdateLabels\x12\x1f.app_server.UpdateLabelsRequest\x1a .app_server.UpdateLabelsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'label_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPDATELABELSREQUEST']._serialized_start=27
  _globals['_UPDATELABELSREQUEST']._serialized_end=89
  _globals['_UPDATELABELSRESPONSE']._serialized_start=91
  _globals['_UPDATELABELSRESPONSE']._serialized_end=147
  _globals['_MESSAGESERVICE']._serialized_start=149
  _globals['_MESSAGESERVICE']._serialized_end=248
# @@protoc_insertion_point(module_scope)
