"""
Metadata Service - Business logic for metadata type management.
Handles CRUD operations for metadata field definitions and validation rules.
"""

import logging
from typing import Optional, List

from app.core.exceptions import (
    ValidationException,
    ConflictException,
    NotFoundException,
    ForbiddenException,
)
from app.models.database import MetadataTypeDocument, AllowedValue
from app.repositories.metadata_repository import MetadataRepository

logger = logging.getLogger(__name__)


def _to_metadata_model(doc: dict) -> Optional[MetadataTypeDocument]:
    """Convert dict to MetadataTypeDocument."""
    if not doc:
        return None
    return MetadataTypeDocument(**doc)


class MetadataService:
    """
    Service for metadata type management.
    Provides business logic for defining and managing metadata field types.
    """
    
    def __init__(self):
        """Initialize MetadataService with repository."""
        self._metadata_repo = None
    
    @property
    def metadata_repo(self) -> MetadataRepository:
        """Lazy load metadata repository."""
        if self._metadata_repo is None:
            self._metadata_repo = MetadataRepository()
        return self._metadata_repo
    
    async def create_metadata_type(
        self,
        key: str,
        display_name: str,
        description: str = "",
        allowed_values: Optional[List[AllowedValue]] = None,
        is_active: bool = True,
        is_system: bool = False,
    ) -> MetadataTypeDocument:
        """
        Create a new metadata type definition.
        
        Args:
            key: Unique metadata key (e.g., 'academic_year', 'cohort', 'access_scope')
            display_name: Display name for UI
            description: Description (auto-generated by Gemini if empty)
            allowed_values: List of AllowedValue objects (None = free text)
                            If any entry has value='all', filter will auto-add OR key='all'
            is_active: If False, hidden from UI
            is_system: If True, cannot be deleted
            
        Returns:
            MetadataTypeDocument: Created metadata type
        """
        # Check if key already exists
        existing = await self.metadata_repo.find_by_key(key)
        if existing:
            raise ConflictException(f"Metadata key '{key}' already exists")
        
        # Convert AllowedValue list to dict list for MongoDB
        allowed_values_dict = None
        if allowed_values is not None:
            allowed_values_dict = [v.to_dict() for v in allowed_values]
        
        # Create metadata type
        metadata_data = {
            "key": key,
            "display_name": display_name,
            "description": description,
            "allowed_values": allowed_values_dict,
            "is_active": is_active,
            "is_system": is_system,
        }

        metadata_doc = await self.metadata_repo.create(metadata_data)
        logger.info(f"Created metadata type: {key}")
        return _to_metadata_model(metadata_doc)

    async def update_metadata_type(
        self,
        key: str,
        display_name: Optional[str] = None,
        description: Optional[str] = None,
        allowed_values: Optional[List[AllowedValue]] = None,
        is_active: Optional[bool] = None,
    ) -> MetadataTypeDocument:
        """
        Update an existing metadata type.
        Cannot update: key (immutable), is_system (immutable after creation).
        """
        existing = await self.metadata_repo.find_by_key(key)
        if not existing:
            raise NotFoundException("MetadataType", key)

        updates = {}
        if display_name is not None:
            updates["display_name"] = display_name
        if description is not None:
            updates["description"] = description
        if allowed_values is not None:
            # Merge incoming allowed_values with existing ones.
            # The `value` field is immutable — only display_name, is_active, color can change.
            # New entries (new value keys) are added; existing entries not in the request are kept.
            existing_values_map = {}
            for av in (existing.get("allowed_values") or []):
                existing_values_map[av["value"]] = av

            for new_av in allowed_values:
                vk = new_av.value
                if vk in existing_values_map:
                    existing_values_map[vk] = {
                        "value": vk,
                        "display_name": new_av.display_name,
                        "is_active": new_av.is_active,
                        "color": new_av.color,
                    }
                else:
                    existing_values_map[vk] = new_av.to_dict()

            updates["allowed_values"] = list(existing_values_map.values())
        if is_active is not None:
            updates["is_active"] = is_active

        if not updates:
            return _to_metadata_model(existing)

        await self.metadata_repo.update_by_key(key, updates)
        updated = await self.metadata_repo.find_by_key(key)
        logger.info(f"Updated metadata type: {key}")
        return _to_metadata_model(updated)

    async def delete_metadata_type(self, key: str) -> MetadataTypeDocument:
        """
        Soft-delete a metadata type by setting is_active=False.

        Raises:
            NotFoundException: If metadata type not found
            ForbiddenException: If is_system=True
        """
        existing = await self.metadata_repo.find_by_key(key)
        if not existing:
            raise NotFoundException("MetadataType", key)

        if existing.get("is_system", False):
            raise ForbiddenException(
                f"Cannot deactivate system metadata type: '{key}'. "
                "System metadata types are protected."
            )

        await self.metadata_repo.update_by_key(key, {"is_active": False})
        updated = await self.metadata_repo.find_by_key(key)
        logger.info(f"Deactivated metadata type: {key}")
        return _to_metadata_model(updated)
    
    async def get_metadata_type(self, key: str) -> Optional[MetadataTypeDocument]:
        """
        Get a metadata type by key.
        
        Args:
            key: Metadata key
            
        Returns:
            MetadataTypeDocument or None
        """
        metadata_doc = await self.metadata_repo.find_by_key(key)
        return _to_metadata_model(metadata_doc)
    
    async def list_all_metadata_types(self, active_only: bool = False) -> List[MetadataTypeDocument]:
        """
        List all metadata types (no pagination) - Phase 4 with active filter.
        
        Args:
            active_only: If True, only return is_active=True metadata types
        
        Returns:
            list: All metadata types (filtered by is_active if requested)
        """
        filter_query = {"is_active": True} if active_only else {}
        types = await self.metadata_repo.find_many(filter_query, 0, 1000, sort=[("created_at", -1)])
        return [_to_metadata_model(t) for t in types]
    
    async def list_metadata_types(
        self,
        skip: int = 0,
        limit: int = 100,
        active_only: bool = False,
    ) -> tuple[List[MetadataTypeDocument], int]:
        """
        List metadata types with pagination - Phase 4 with active filter.
        
        Args:
            skip: Number of records to skip
            limit: Maximum records to return
            active_only: If True, only return is_active=True metadata types
            
        Returns:
            tuple: (metadata_types, total_count)
        """
        filter_query = {"is_active": True} if active_only else {}
        types = await self.metadata_repo.find_many(filter_query, skip, limit, sort=[("created_at", -1)])
        total = await self.metadata_repo.count(filter_query)
        
        result = [_to_metadata_model(t) for t in types]
        return result, total
    
    async def get_all_keys(self) -> list[str]:
        """Get all registered metadata keys."""
        return await self.metadata_repo.get_all_keys()
    
    async def validate_metadata(self, metadata: dict) -> tuple[bool, list[str]]:
        """
        Validate metadata values against defined types and rules - Phase 4 refactored.
        
        Changes:
        - Group validation: academic_year OR cohort required
        - Required: access_scope (bắt buộc)
        - Check metadata type is_active=True
        - Check value exists in allowed_values AND AllowedValue.is_active=True
        - Use AllowedValue.value (not display_name) for comparison
        
        Args:
            metadata: Metadata dictionary to validate
            
        Returns:
            tuple: (is_valid, error_messages)
        """
        errors = []

        # Get all registered metadata types
        all_metadata_types = await self.list_all_metadata_types(active_only=False)
        metadata_types_map = {mt.key: mt for mt in all_metadata_types}
        
        for key, value in metadata.items():
            # Check if key is registered
            if key not in metadata_types_map:
                errors.append(f"Unknown metadata key: '{key}'")
                continue
            
            meta_type = metadata_types_map[key]
            
            # Check if metadata type is active
            if not meta_type.is_active:
                errors.append(f"Metadata type '{key}' is not active")
                continue
            
            # Get allowed values
            allowed_values_list = meta_type.get_allowed_values()
            
            # If allowed_values is None, any value is accepted (free text)
            if allowed_values_list is None:
                continue
            
            # Check if value is in allowed_values and is active
            active_allowed_values = [av for av in allowed_values_list if av.is_active]
            active_values = [av.value for av in active_allowed_values]
            
            # Handle single value vs list
            if isinstance(value, list):
                for v in value:
                    if v not in active_values:
                        errors.append(
                            f"Invalid value '{v}' for metadata '{key}'. "
                            f"Allowed active values: {active_values}"
                        )
            else:
                if value not in active_values:
                    errors.append(
                        f"Invalid value '{value}' for metadata '{key}'. "
                        f"Allowed active values: {active_values}"
                    )
        
        return len(errors) == 0, errors


def get_metadata_service() -> MetadataService:
    """Get MetadataService instance."""
    return MetadataService()
