"""
Metadata Service - Business logic for metadata type management.
Handles CRUD operations for metadata field definitions and validation rules.
"""

import logging
from typing import List, Optional, Dict, Any

from app.core.exceptions import (
    ValidationException,
    ConflictException,
    NotFoundException,
    ForbiddenException,
)
from app.models.database import MetadataTypeDocument, AllowedValue
from app.repositories.metadata_repository import MetadataRepository

logger = logging.getLogger(__name__)


def _to_metadata_model(doc: dict) -> Optional[MetadataTypeDocument]:
    """Convert dict to MetadataTypeDocument."""
    if not doc:
        return None
    return MetadataTypeDocument(**doc)


class MetadataService:
    """
    Service for metadata type management.
    Provides business logic for defining and managing metadata field types.
    """
    
    def __init__(self):
        """Initialize MetadataService with repository."""
        self._metadata_repo = None
    
    @property
    def metadata_repo(self) -> MetadataRepository:
        """Lazy load metadata repository."""
        if self._metadata_repo is None:
            self._metadata_repo = MetadataRepository()
        return self._metadata_repo
    
    async def create_metadata_type(
        self,
        key: str,
        display_name: str,
        description: str = "",
        allowed_values: Optional[List[AllowedValue]] = None,
        is_active: bool = True,
        is_system: bool = False,
    ) -> MetadataTypeDocument:
        """
        Create a new metadata type definition.
        
        Args:
            key: Unique metadata key (e.g., 'academic_year', 'cohort', 'access_scope')
            display_name: Display name for UI
            description: Description (auto-generated by Gemini if empty)
            allowed_values: List of AllowedValue objects (None = free text)
                            If any entry has value='all', filter will auto-add OR key='all'
            is_active: If False, hidden from UI
            is_system: If True, cannot be deleted
            
        Returns:
            MetadataTypeDocument: Created metadata type
        """
        # Check if key already exists
        existing = await self.metadata_repo.find_by_key(key)
        if existing:
            raise ConflictException(f"Metadata key '{key}' already exists")
        
        # Convert AllowedValue list to dict list for MongoDB
        allowed_values_dict = None
        if allowed_values is not None:
            for av in allowed_values:
                # CRITICAL: visible_roles is mandatory and cannot be empty
                if not av.visible_roles:
                    raise ValidationException(f"visible_roles is mandatory and cannot be empty for value '{av.value}'")
            allowed_values_dict = [v.to_dict() for v in allowed_values]
        
        # Create metadata type
        metadata_data = {
            "key": key,
            "display_name": display_name,
            "description": description,
            "allowed_values": allowed_values_dict,
            "is_active": is_active,
            "is_system": is_system,
        }

        metadata_doc = await self.metadata_repo.create(metadata_data)
        logger.info(f"Created metadata type: {key}")
        return _to_metadata_model(metadata_doc)

    async def update_metadata_type(
        self,
        key: str,
        display_name: Optional[str] = None,
        description: Optional[str] = None,
        is_active: Optional[bool] = None,
    ) -> MetadataTypeDocument:
        """
        Update an existing metadata type top-level properties.
        Cannot update: key (immutable), is_system (immutable after creation), allowed_values (use separate APIs).
        """
        existing = await self.metadata_repo.find_by_key(key)
        if not existing:
            raise NotFoundException("MetadataType", key)

        updates = {}
        if display_name is not None:
            updates["display_name"] = display_name
        if description is not None:
            updates["description"] = description
        if is_active is not None:
            updates["is_active"] = is_active

        if not updates:
            return _to_metadata_model(existing)

        await self.metadata_repo.update_by_key(key, updates)
        updated = await self.metadata_repo.find_by_key(key)
        logger.info(f"Updated metadata type properties: {key}")
        return _to_metadata_model(updated)

    async def add_metadata_value(
        self,
        key: str,
        allowed_value: AllowedValue
    ) -> MetadataTypeDocument:
        """Add a new allowed value to a metadata type."""
        existing = await self.metadata_repo.find_by_key(key)
        if not existing:
            raise NotFoundException("MetadataType", key)
            
        if not allowed_value.visible_roles:
            raise ValidationException(f"visible_roles is mandatory and cannot be empty for value '{allowed_value.value}'")

        existing_values = existing.get("allowed_values") or []
        
        # Check if value already exists
        for av in existing_values:
            if av["value"] == allowed_value.value:
                raise ConflictException(f"Allowed value '{allowed_value.value}' already exists in metadata type '{key}'")
                
        existing_values.append(allowed_value.to_dict())
        
        await self.metadata_repo.update_by_key(key, {"allowed_values": existing_values})
        updated = await self.metadata_repo.find_by_key(key)
        logger.info(f"Added metadata value '{allowed_value.value}' to type '{key}'")
        return _to_metadata_model(updated)

    async def update_metadata_value(
        self,
        key: str,
        value_key: str,
        display_name: Optional[str] = None,
        is_active: Optional[bool] = None,
        color: Optional[str] = None,
        visible_roles: Optional[list[str]] = None,
    ) -> MetadataTypeDocument:
        """Update properties of an existing allowed value."""
        existing = await self.metadata_repo.find_by_key(key)
        if not existing:
            raise NotFoundException("MetadataType", key)

        existing_values = existing.get("allowed_values") or []
        target_idx = -1
        
        for i, av in enumerate(existing_values):
            if av["value"] == value_key:
                target_idx = i
                break
                
        if target_idx == -1:
            raise NotFoundException(f"Metadata value '{value_key}' in type '{key}'", value_key)

        av = existing_values[target_idx]
        
        if display_name is not None:
            av["display_name"] = display_name
        if is_active is not None:
            av["is_active"] = is_active
        if color is not None:
            av["color"] = color
        if visible_roles is not None:
            if not visible_roles:
                raise ValidationException(f"visible_roles is mandatory and cannot be empty for value '{value_key}'")
            av["visible_roles"] = visible_roles

        await self.metadata_repo.update_by_key(key, {"allowed_values": existing_values})
        updated = await self.metadata_repo.find_by_key(key)
        logger.info(f"Updated metadata value '{value_key}' in type '{key}'")
        return _to_metadata_model(updated)

    async def delete_metadata_type(self, key: str) -> None:
        """
        Hard-delete a metadata type. Can only delete if total_files == 0.

        Raises:
            NotFoundException: If metadata type not found
            ForbiddenException: If is_system=True
            ConflictException: If total_files > 0
        """
        existing = await self.metadata_repo.find_by_key(key)
        if not existing:
            raise NotFoundException("MetadataType", key)

        if existing.get("is_system", False):
            raise ForbiddenException(
                f"Cannot delete system metadata type: '{key}'. "
                "System metadata types are protected."
            )
            
        if existing.get("total_files", 0) > 0:
            raise ConflictException(
                f"Cannot delete metadata type '{key}' because it is in use by {existing.get('total_files')} files."
            )

        await self.metadata_repo.delete_by_key(key)
        logger.info(f"Hard-deleted metadata type: {key}")

    async def delete_metadata_value(self, key: str, value: str) -> MetadataTypeDocument:
        """
        Hard-delete a metadata value from allowed_values. Can only delete if total_files == 0 for this value.
        
        Raises:
            NotFoundException: If metadata type not found
            ConflictException: If value total_files > 0 or value not found
        """
        existing = await self.metadata_repo.find_by_key(key)
        if not existing:
            raise NotFoundException("MetadataType", key)
            
        allowed_values = existing.get("allowed_values") or []
        target_value = next((v for v in allowed_values if v["value"] == value), None)
        
        if not target_value:
            raise NotFoundException(f"Metadata value '{value}' in type '{key}'", value)
            
        if target_value.get("total_files", 0) > 0:
            raise ConflictException(
                f"Cannot delete metadata value '{value}' because it is in use by {target_value.get('total_files')} files."
            )
            
        # Remove target value
        allowed_values = [v for v in allowed_values if v["value"] != value]
        
        await self.metadata_repo.update_by_key(key, {"allowed_values": allowed_values})
        updated = await self.metadata_repo.find_by_key(key)
        logger.info(f"Hard-deleted metadata value: {value} from type {key}")
        return _to_metadata_model(updated)
    
    async def get_metadata_type(self, key: str) -> Optional[MetadataTypeDocument]:
        """
        Get a metadata type by key.
        
        Args:
            key: Metadata key
            
        Returns:
            MetadataTypeDocument or None
        """
        metadata_doc = await self.metadata_repo.find_by_key(key)
        return _to_metadata_model(metadata_doc)
    
    async def list_all_metadata_types(self, active_only: bool = False) -> List[MetadataTypeDocument]:
        """
        List all metadata types (no pagination) - Phase 4 with active filter.
        
        Args:
            active_only: If True, only return is_active=True metadata types
        
        Returns:
            list: All metadata types (filtered by is_active if requested)
        """
        filter_query = {"is_active": True} if active_only else {}
        types = await self.metadata_repo.find_many(filter_query, 0, 1000, sort=[("created_at", -1)])
        return [_to_metadata_model(t) for t in types]
    
    async def list_metadata_types(
        self,
        skip: int = 0,
        limit: int = 100,
        active_only: bool = False,
    ) -> tuple[List[MetadataTypeDocument], int]:
        """
        List metadata types with pagination - Phase 4 with active filter.
        
        Args:
            skip: Number of records to skip
            limit: Maximum records to return
            active_only: If True, only return is_active=True metadata types
            
        Returns:
            tuple: (metadata_types, total_count)
        """
        filter_query = {"is_active": True} if active_only else {}
        types = await self.metadata_repo.find_many(filter_query, skip, limit, sort=[("created_at", -1)])
        total = await self.metadata_repo.count(filter_query)
        
        result = [_to_metadata_model(t) for t in types]
        return result, total
    
    async def get_all_keys(self) -> list[str]:
        """Get all registered metadata keys."""
        return await self.metadata_repo.get_all_keys()
    
    async def validate_metadata(self, metadata: dict) -> tuple[bool, list[str]]:
        """
        Validate metadata values against defined types and rules - Phase 4 refactored.
        
        Changes:
        - Group validation: academic_year OR cohort required
        - Required: access_scope (bắt buộc)
        - Check metadata type is_active=True
        - Check value exists in allowed_values AND AllowedValue.is_active=True
        - Use AllowedValue.value (not display_name) for comparison
        
        Args:
            metadata: Metadata dictionary to validate
            
        Returns:
            tuple: (is_valid, error_messages)
        """
        errors = []

        # Get all registered metadata types
        all_metadata_types = await self.list_all_metadata_types(active_only=False)
        metadata_types_map = {mt.key: mt for mt in all_metadata_types}
        
        for key, value in metadata.items():
            # Check if key is registered
            if key not in metadata_types_map:
                errors.append(f"Unknown metadata key: '{key}'")
                continue
            
            meta_type = metadata_types_map[key]
            
            # Check if metadata type is active
            if not meta_type.is_active:
                errors.append(f"Metadata type '{key}' is not active")
                continue
            
            # Get allowed values
            allowed_values_list = meta_type.get_allowed_values()
            
            # If allowed_values is None, any value is accepted (free text)
            if allowed_values_list is None:
                continue
            
            # Check if value is in allowed_values and is active
            active_allowed_values = [av for av in allowed_values_list if av.is_active]
            active_values = [av.value for av in active_allowed_values]
            
            # Handle single value vs list
            if isinstance(value, list):
                errors.append(f"Metadata '{key}' does not support multiple values (arrays are not allowed).")
                continue
            
            if value not in active_values:
                errors.append(
                    f"Invalid value '{value}' for metadata '{key}'. "
                    f"Allowed active values: {active_values}"
                )
        
        return len(errors) == 0, errors

    async def sync_metadata_counters(self, custom_metadata: dict, delta: int) -> None:
        """
        Sync metadata total_files counters.
        Delegates to MetadataRepository.
        
        Args:
            custom_metadata: Dictionary of current file custom metadata
            delta: +1 for new file, -1 for deleted/deactivated file
        """
        await self.metadata_repo.sync_metadata_counters(custom_metadata, delta)
        
    async def get_metadata_types_by_keys(self, keys: list[str]) -> List[MetadataTypeDocument]:
        """
        Fetch metadata types by a list of keys.
        
        Args:
            keys: List of metadata keys to fetch
            
        Returns:
            List of matching MetadataTypeDocument objects
        """
        if not keys:
            return []
        
        types = await self.metadata_repo.find_many({"key": {"$in": keys}})
        return [_to_metadata_model(t) for t in types]

    async def validate_file_metadata_requirements(self, custom_metadata: Dict[str, Any]) -> None:
        """
        Validate file metadata requirements (system fields and value validation).
        Rules:
        - All system metadata fields are required.
        - Exception: At least one of academic_year or cohort is required.
        """
        from app.core.exceptions import ValidationException
        if not custom_metadata:
            custom_metadata = {}

        # 1. Get all system metadata types
        all_types = await self.list_all_metadata_types(active_only=True)
        system_types = [mt for mt in all_types if mt.is_system]
        
        # 2. Separate standard system keys from the academic/cohort pair
        standard_system_keys = [
            mt.key for mt in system_types 
            if mt.key not in ["academic_year", "cohort"]
        ]
        
        # 3. Check standard system keys are present
        for key in standard_system_keys:
            if key not in custom_metadata:
                raise ValidationException(f"Metadata '{key}' is required (system metadata).")
        
        # 4. Check academic_year or cohort (at least one required if they are system types)
        is_academic_system = any(mt.key == "academic_year" for mt in system_types)
        is_cohort_system = any(mt.key == "cohort" for mt in system_types)
        
        if (is_academic_system or is_cohort_system) and ("academic_year" not in custom_metadata and "cohort" not in custom_metadata):
            raise ValidationException(
                "Metadata must include at least one of 'academic_year' or 'cohort'."
            )

        # 5. Value validation against registered metadata types
        is_valid, errors = await self.validate_metadata(custom_metadata)

        if not is_valid:
            error_msg = "; ".join(errors)
            raise ValidationException(f"Metadata validation failed: {error_msg}")

    async def filter_custom_metadata_by_role(self, file_dicts: List[Dict[str, Any]], user_role: str) -> None:
        """Filter out metadata keys from custom_metadata based on visible_roles."""
        if not file_dicts:
            return
            
        # Collect all metadata keys
        keys_to_fetch = set()
        for f in file_dicts:
            cm = f.get("custom_metadata") or {}
            keys_to_fetch.update(cm.keys())
            
        if not keys_to_fetch:
            return
            
        all_metadata = await self.get_metadata_types_by_keys(list(keys_to_fetch))
        
        meta_map = {}
        for meta in all_metadata:
            key = meta.key
            allowed_values = meta.get_allowed_values() or []
            values_map = {av.value: av.visible_roles for av in allowed_values}
            meta_map[key] = values_map
            
        for f in file_dicts:
            cm = f.get("custom_metadata") or {}
            if not cm:
                continue
                
            filtered_cm = {}
            for k, v in cm.items():
                roles = meta_map.get(k, {}).get(v)
                if roles is None:
                    # Value not found in allowed_values, keep it
                    filtered_cm[k] = v
                elif user_role in roles:
                    filtered_cm[k] = v
            f["custom_metadata"] = filtered_cm
        

def get_metadata_service() -> MetadataService:
    """Get MetadataService instance."""
    return MetadataService()
