# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\napp_server\"+\n\x16GetMessageStateRequest\x12\x11\n\tmessageId\x18\x01 \x01(\x05\"@\n\x17GetMessageStateResponse\x12\x11\n\tisCurrent\x18\x01 \x01(\x08\x12\x12\n\nhasRecords\x18\x02 \x01(\x08\x32g\n\x0eMessageService\x12U\n\x08GetState\x12\".app_server.GetMessageStateRequest\x1a#.app_server.GetMessageStateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETMESSAGESTATEREQUEST']._serialized_start=29
  _globals['_GETMESSAGESTATEREQUEST']._serialized_end=72
  _globals['_GETMESSAGESTATERESPONSE']._serialized_start=74
  _globals['_GETMESSAGESTATERESPONSE']._serialized_end=138
  _globals['_MESSAGESERVICE']._serialized_start=140
  _globals['_MESSAGESERVICE']._serialized_end=243
# @@protoc_insertion_point(module_scope)
