# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\napp_server\"#\n\x12VerifyTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x84\x01\n\x13VerifyTokenResponse\x12=\n\x07payload\x18\x01 \x03(\x0b\x32,.app_server.VerifyTokenResponse.PayloadEntry\x1a.\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32]\n\x0b\x41uthService\x12N\n\x0bVerifyToken\x12\x1e.app_server.VerifyTokenRequest\x1a\x1f.app_server.VerifyTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFYTOKENRESPONSE_PAYLOADENTRY']._loaded_options = None
  _globals['_VERIFYTOKENRESPONSE_PAYLOADENTRY']._serialized_options = b'8\001'
  _globals['_VERIFYTOKENREQUEST']._serialized_start=26
  _globals['_VERIFYTOKENREQUEST']._serialized_end=61
  _globals['_VERIFYTOKENRESPONSE']._serialized_start=64
  _globals['_VERIFYTOKENRESPONSE']._serialized_end=196
  _globals['_VERIFYTOKENRESPONSE_PAYLOADENTRY']._serialized_start=150
  _globals['_VERIFYTOKENRESPONSE_PAYLOADENTRY']._serialized_end=196
  _globals['_AUTHSERVICE']._serialized_start=198
  _globals['_AUTHSERVICE']._serialized_end=291
# @@protoc_insertion_point(module_scope)
