# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: email.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'email.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65mail.proto\x12\napp_server\"U\n\x17\x43reateEmailDraftRequest\x12\x11\n\tmessageId\x18\x01 \x01(\x05\x12\x14\n\x0c\x64raftSubject\x18\x02 \x01(\t\x12\x11\n\tdraftBody\x18\x03 \x01(\t\"+\n\x18\x43reateEmailDraftResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32h\n\x0c\x45mailService\x12X\n\x0b\x43reateDraft\x12#.app_server.CreateEmailDraftRequest\x1a$.app_server.CreateEmailDraftResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'email_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEEMAILDRAFTREQUEST']._serialized_start=27
  _globals['_CREATEEMAILDRAFTREQUEST']._serialized_end=112
  _globals['_CREATEEMAILDRAFTRESPONSE']._serialized_start=114
  _globals['_CREATEEMAILDRAFTRESPONSE']._serialized_end=157
  _globals['_EMAILSERVICE']._serialized_start=159
  _globals['_EMAILSERVICE']._serialized_end=263
# @@protoc_insertion_point(module_scope)
